version: "3"
services:
  postgresdbserver:
    image: postgres:9.6.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=sysml2
    ports:
      - "5433:5433"
    volumes:
      - postgres_server_selab:/var/lib/postgresql/data
    networks:
      - digital_env

  sysmlapiserver:
    build:
      context: .
      dockerfile: Dockerfile.api
    tty: true
    depends_on:
      - postgresdbserver
    ports:
      - "9000:9000"
    restart: always
    networks:
      - digital_env

  tljh:
    build:
      context: .
      dockerfile: Dockerfile.tljh
    privileged: true
    restart: always
    ports:
      - 8889:80
    environment:
      TZ: UTC/NEW_YORK
    volumes:
      - ./config/config.yaml:/opt/tljh/config/config.yaml
      - ./envs:/tmp/envs/
      - ./updates:/tmp/updates/
      - user_data_selab:/home
    networks:
      - digital_env

networks:
  digital_env:
    external: true

volumes:
  postgres_server_selab:
    external: true
  user_data_selab:
    external: true
  # This volume is used to persist user data across container restarts.